version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API 接口端口（Go 程序访问）
      - "9001:9001"  # 控制台端口（浏览器访问）
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    restart: always
    networks:
      - cloud-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cloud-storage
      MYSQL_USER: cloud-storage
      MYSQL_PASSWORD: cloud-storage
    volumes:
      - /home/haobin/桌面/docker-mysql-data/cloude-storage:/var/lib/mysql
    restart: always
    networks:
      - cloud-net
  etcd:
      container_name: etcd
      image: quay.io/coreos/etcd:v3.5.5
      ports:
        - "2379:2379"  # 客户端访问端口
        - "2380:2380"  # 节点间通信端口
      volumes:
        - ./etcd/data:/etcd-data
      environment:
        - ETCDCTL_API=3
        - ETCD_DATA_DIR=/etcd-data
        - ETCD_NAME=node1
        - ETCD_ADVERTISE_CLIENT_URLS=http://localhost:2379
        - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
        - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
        - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      networks:
        - cloud-net

networks:
  cloud-net:
    driver: bridge